# This repo runs the same hooks on itself via a `local` repo in `prek.toml`.
# Keep all hooks, and their fields, synced between the two files.

- description: Forbid tabs except those used for indentation.
  id: no-inline-tabs
  name: check for inline tabs
  entry: '^\t*[^\t].*\t'
  language: pygrep
  types:
    - text

- description: Prevent autosquash commits from being pushed.
  id: no-autosquash-commits
  name: check for autosquash commits
  entry: hooks/no-autosquash-commits.py
  language: script
  stages:
    - pre-push
  always_run: true
  pass_filenames: false

- description: Check that scaffolding files are in sync with `sg`.
  id: sg-status
  name: check scaffolding compliance
  entry: sg status --only-drifts
  language: python
  stages:
    - pre-push
  always_run: true
  pass_filenames: false

- description: Check that scaffolding files are valid
  id: sg-validate
  name: check scaffolding validity
  entry: sg validate --only-fails
  language: python
  stages:
    - pre-push
  always_run: true
  pass_filenames: false
