"""The `sg` command-line interface."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

from styleguide.types.repo import Repo

app = typer.Typer(
	help="Keep scaffolding consistent across my projects.",
	rich_markup_mode="rich",
	no_args_is_help=True,
)
console = Console()


@app.callback()
def main() -> None:
	"""Keep scaffolding consistent across my projects."""


@app.command()
def status(
	repo: Annotated[
		Path,
		typer.Argument(help="path to the target repo"),
	] = Path(),
	show_diff: Annotated[
		bool,
		typer.Option("--diff/--no-diff", help="show preview for drifted files"),
	] = False,
	show_only_drifts: Annotated[
		bool,
		typer.Option("--only-drifts/--all", help="show only the drifted files"),
	] = False,
) -> None:
	"""
	Report scaffolding status for a repo. This script exits with non-zero status
	code if there are drifted or unmanaged files.
	"""
	try:
		target_repo = Repo(repo)
	except ValueError as e:
		console.print(f"[red]{e}[/red]")
		raise typer.Exit(2) from e

	for item in target_repo.display_status(
		show_diff=show_diff,
		show_only_drifts=show_only_drifts,
	):
		console.print(item)

	if target_repo.has_drift or target_repo.unmanaged_files:
		raise typer.Exit(1)


@app.command()
def sync(
	repo: Annotated[
		Path,
		typer.Argument(help="path to the target repo"),
	] = Path(),
	show_diff: Annotated[
		bool,
		typer.Option("--diff/--no-diff", help="show diffs when applying"),
	] = False,
	assume_yes: Annotated[
		bool,
		typer.Option("--yes/--ask", help="write all without confirmation"),
	] = False,
) -> None:
	"""
	Bring a repo's managed files up to date by regenerating them against the
	base templates.
	"""
	try:
		target_repo = Repo(repo)
	except ValueError as e:
		console.print(f"[red]{e}[/red]")
		raise typer.Exit(2) from e

	for item in target_repo.perform_sync(
		assume_yes=assume_yes,
		show_diff=show_diff,
		console=console,
	):
		console.print(item)


@app.command()
def validate(
	repo: Annotated[
		Path,
		typer.Argument(help="path to the target repo"),
	] = Path(),
	show_only_fails: Annotated[
		bool,
		typer.Option("--only-fails/--all", help="show only files that fail validation"),
	] = False,
) -> None:
	"""
	Validate files that are not generated by `sg` still conform to the styleguide.
	"""

	try:
		target_repo = Repo(repo)
	except ValueError as e:
		console.print(f"[red]{e}[/red]")
		raise typer.Exit(2) from e

	output, exit_code = target_repo.perform_validation(
		show_only_fails=show_only_fails,
	)
	for item in output:
		console.print(item)

	raise typer.Exit(exit_code)
